
name: Deploy Databricks Notebook

on:
  push:
    branches:
      - main  # Runs when code is merged into main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Databricks CLI
      run: pip install databricks-cli

    - name: Configure Databricks CLI
      run: |
        mkdir -p ~/.databricks
        echo "[DEFAULT]" > ~/.databricks/config
        echo "host = ${{ secrets.DATABRICKS_HOST }}" >> ~/.databricks/config
        echo "token = ${{ secrets.DATABRICKS_TOKEN }}" >> ~/.databricks/config

    - name: Deploy Notebook
      run: |
        databricks workspace import \
          --language PYTHON \
          --overwrite \
          notebooks/my_notebook.py \
          /Workspace/Shared/my_notebook
